"""Stub generation for adjacent migrations."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .exceptions import InvalidMigrationError
from .registry import MigrationRegistry
from .versioning import VersionedModel


@dataclass(frozen=True, slots=True)
class GeneratedStub:
    """Metadata about a generated migration stub."""

    path: Path
    schema_name: str
    from_version: int
    to_version: int


def generate_adjacent_migration_stub(
    output_dir: str | Path,
    *,
    from_model: type[VersionedModel],
    to_model: type[VersionedModel],
    overwrite: bool = False,
) -> GeneratedStub:
    from_schema = from_model.schema_id()
    to_schema = to_model.schema_id()

    if from_schema.schema_name != to_schema.schema_name:
        raise InvalidMigrationError("adjacent stubs must stay within a single schema family")
    if not from_schema.is_adjacent_to(to_schema):
        raise InvalidMigrationError("stub generation only supports adjacent schema versions")

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    file_name = f"{_slugify(from_schema.schema_name)}_v{from_schema.version}_to_v{to_schema.version}.py"
    file_path = output_path / file_name
    if file_path.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing migration stub: {file_path}")

    file_path.write_text(
        _render_stub(from_model=from_model, to_model=to_model),
        encoding="utf-8",
    )

    return GeneratedStub(
        path=file_path,
        schema_name=from_schema.schema_name,
        from_version=from_schema.version,
        to_version=to_schema.version,
    )


def generate_bidirectional_migration_stubs(
    output_dir: str | Path,
    *,
    older_model: type[VersionedModel],
    newer_model: type[VersionedModel],
    overwrite: bool = False,
) -> tuple[GeneratedStub, GeneratedStub]:
    older_schema = older_model.schema_id()
    newer_schema = newer_model.schema_id()

    if older_schema.version >= newer_schema.version:
        raise InvalidMigrationError("older_model must have a lower version than newer_model")

    return (
        generate_adjacent_migration_stub(
            output_dir,
            from_model=older_model,
            to_model=newer_model,
            overwrite=overwrite,
        ),
        generate_adjacent_migration_stub(
            output_dir,
            from_model=newer_model,
            to_model=older_model,
            overwrite=overwrite,
        ),
    )


def generate_missing_adjacent_migration_stubs(
    output_dir: str | Path,
    *,
    registry: MigrationRegistry,
    schema_name: str,
    overwrite: bool = False,
    require_bidirectional: bool = True,
) -> tuple[GeneratedStub, ...]:
    stubs: list[GeneratedStub] = []
    for missing in registry.missing_adjacent_migrations(
        schema_name,
        require_bidirectional=require_bidirectional,
    ):
        stubs.append(
            generate_adjacent_migration_stub(
                output_dir,
                from_model=missing.from_model,
                to_model=missing.to_model,
                overwrite=overwrite,
            )
        )
    return tuple(stubs)


def _render_stub(*, from_model: type[VersionedModel], to_model: type[VersionedModel]) -> str:
    from_schema = from_model.schema_id()
    to_schema = to_model.schema_id()
    function_name = (
        f"migrate_{_slugify(from_schema.schema_name)}_v{from_schema.version}_to_v{to_schema.version}"
    )

    return f'''"""Adjacent migration stub for {from_schema.schema_name} v{from_schema.version} -> v{to_schema.version}.

Generated by pydantic-migrator. Fill in the transformation logic below.
"""

from __future__ import annotations

from {from_model.__module__} import {from_model.__name__}
from {to_model.__module__} import {to_model.__name__}
from pydantic_migrator import define_migration


@define_migration(
    from_model={from_model.__name__},
    to_model={to_model.__name__},
)
def {function_name}(model: {from_model.__name__}) -> {to_model.__name__}:
    """Transform `{from_model.__name__}` into `{to_model.__name__}`."""
    # TODO: map source fields into the target model.
    # TODO: replace this placeholder with domain-specific migration logic.
    raise NotImplementedError(
        "TODO: implement {from_schema.schema_name} migration from "
        "v{from_schema.version} to v{to_schema.version}"
    )
'''


def _slugify(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", value).strip("_").lower()
